server:
  port: 9098  #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: https://eureka-server-letscode.herokuapp.com
    healthcheck:
      enabled: true
    lease:
      duration: 5